server:
port: 8089

ollama:
  base-url: ${OLLAMA_BASE_URL:http://localhost:11435}
  model: ${OLLAMA_MODEL:llama2}
  # system prompt is optional
  system-prompt: ${OLLAMA_SYSTEM_PROMPT:You are a concise helpful assistant.}
  timeout-ms: ${OLLAMA_TIMEOUT_MS:60000}
